name: Feature Request
description: Request a feature here
title: "[Feature]: "
labels: ["feature"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    attributes:
      label: Write your feature request here.
      description: |
        Write your feature request here...
    validations:
      required: true
